# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: I am facing some problems.
title: "[Bug] %%Package Name%%"
labels: ["bug"]
assignees:
  - JaimeZeng
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit you issue using the following template!
        By opening this issue you confirm that you have searched for similar issues/PRs here already.
        Failing to do so will most likely result in closing of this issue without any explanation.
        Incomplete form details below might also result in closing of the issue.
  - type: input
    id: name
    attributes:
      label: Package Name
      description: "name of package which has bug(s)."
      placeholder: ex. git
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: "A clear and concise description of the behaviour."
      placeholder: |
        current behaviour...
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: "A clear and concise description of what you expected to happen."
      placeholder: |
        expected behaviour...
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Additional context/output
      description: "Add any other context about the problem here. If applicable, paste terminal output here to help explain."
      placeholder: |
        paste terminal output here...
      render: powershell
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: "Only if you have suggestions on a fix for the bug."
      render: powershell
    validations:
      required: false
  - type: dropdown
    id: windows-version
    attributes:
      label: Windows version
      multiple: true
      options:
        - Windows 7
        - Windows 8
        - Windows 10
        - Windows 11
    validations:
      required: true
  - type: dropdown
    id: os-architecture
    attributes:
      label: OS architecture
      multiple: true
      options:
        - 32bit
        - 64bit
    validations:
      required: true
  - type: input
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: Output of `"$($PSVersionTable.PSVersion)"`
      placeholder: 7.2.1
    validations:
      required: true
  - type: textarea
    id: additional-software
    attributes:
      label: Additional software
      description: "(optional) e.g. ConEmu, Git."
    validations:
      required: false
  - type: textarea
    id: scoop-configuration
    attributes:
      label: Scoop Configuration
      description: "Can be found in `~/.config/scoop/config.json`"
      placeholder: "//# Your configuration here"
      render: json
    validations:
      required: false
